apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: simulator-poste
  labels:
    app: simulator-poste-backend
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  OIDC_ISSUER: "https://asojzafbi.accounts.ondemand.com"
  # Frontend URL for CORS
  FRONTEND_URL: "https://simulator-poste.c-6dc1be8.kyma.ondemand.com"
