apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: simulator-poste
  labels:
    app: simulator-poste-frontend
spec:
  type: ClusterIP
  selector:
    app: simulator-poste-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
